### ISSUE TITLE
Remove dependency on the Anaconda website.

### ISSUE THREAD

**Issue by DougRzz** [jupyterlite/xeus-python-kernel#51]
## Description

During the build, using this command in Miniforge, `jupyter lite build  --XeusPythonEnv.packages=ipyvuetify,ipywidgets,ipyflex, numpy, plotly, pandas` I get the following error message (see below). I believe this is because of the settings on my company laptop that prohibits me from visiting the Anaconda website. Is there a way I could get around this issue?

### Error message:

emscripten-forge/emscrip Using cache
emscripten-forge/noarch  Using cache
conda-forge/emscripten-3 [====================] (00m:00s) 404 Failed
pkgs/main/noarch         [>                   ] (00m:08s) Failure when receiving data from the peer
pkgs/r/emscripten-32     [>                   ] (00m:08s) Failure when receiving data from the peer
pkgs/main/emscripten-32  [>                   ] (00m:08s) Failure when receiving data from the peer
pkgs/r/noarch            [>                   ] (00m:07s) Failure when receiving data from the peer
pkgs/msys2/emscripten-32 [>                   ] (00m:07s) Failure when receiving data from the peer
pkgs/msys2/noarch        [>                   ] (00m:07s) Failure when receiving data from the peer
conda-forge/noarch       [                    ] (00m:04s) 2 MB / ?? (236.52 KB/s)

>>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "C:\Users\reddeda\AppData\Local\Continuum\miniconda3\lib\site-packages\conda\exceptions.py", line 1080, in __call__
        return func(*args, **kwargs)
      File "C:\Users\reddeda\AppData\Local\Continuum\miniconda3\lib\site-packages\mamba\mamba.py", line 898, in exception_converter
        raise e
      File "C:\Users\reddeda\AppData\Local\Continuum\miniconda3\lib\site-packages\mamba\mamba.py", line 892, in exception_converter
        exit_code = _wrapped_main(*args, **kwargs)
      File "C:\Users\reddeda\AppData\Local\Continuum\miniconda3\lib\site-packages\mamba\mamba.py", line 851, in _wrapped_main
        result = do_call(args, p)
      File "C:\Users\reddeda\AppData\Local\Continuum\miniconda3\lib\site-packages\mamba\mamba.py", line 732, in do_call
        exit_code = install(args, parser, "install")
      File "C:\Users\reddeda\AppData\Local\Continuum\miniconda3\lib\site-packages\mamba\mamba.py", line 515, in install
        index = load_channels(pool, channels, repos)
      File "C:\Users\reddeda\AppData\Local\Continuum\miniconda3\lib\site-packages\mamba\utils.py", line 106, in load_channels
        use_cache=use_cache,
      File "C:\Users\reddeda\AppData\Local\Continuum\miniconda3\lib\site-packages\mamba\utils.py", line 81, in get_index        is_downloaded = dlist.download(True)
    RuntimeError: Download error (56) Failure when receiving data from the peer [**https://repo.anaconda.com/pkgs/main/noarch/repodata.json**]
    Received HTTP code 403 from proxy after CONNECT

**Comment by DerThorsten** [comment]
Hi @DougRzz

In xeus-python we use conda-forge / emscripten-forge to get the needed packages. 
Unfortunately we need to download the `repodata` from `https://repo.anaconda.com/pkgs/main/noarch/repodata.json`.
